version: "3"

services:
  clickhouse:
    image: yandex/clickhouse-server:20.8.7.15
    volumes:
      - ./resources/init:/docker-entrypoint-initdb.d
      - ./resources/queries:/opt/queries
    tmpfs:
      - /var/lib/clickhouse

  mongo:
    image: mongo:4.4.3
    ports:
      - 9000:9000
    volumes:
      - ./resources/scripts:/opt/resources/scripts
    tmpfs:
      - /data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081